// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"project/src/models/ent/company"
	"project/src/models/ent/permission"
	"project/src/models/ent/role"
	"project/src/models/ent/rolepermission"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// RolePermissionCreate is the builder for creating a RolePermission entity.
type RolePermissionCreate struct {
	config
	mutation *RolePermissionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (rpc *RolePermissionCreate) SetCreatedAt(t time.Time) *RolePermissionCreate {
	rpc.mutation.SetCreatedAt(t)
	return rpc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (rpc *RolePermissionCreate) SetNillableCreatedAt(t *time.Time) *RolePermissionCreate {
	if t != nil {
		rpc.SetCreatedAt(*t)
	}
	return rpc
}

// SetUpdatedAt sets the "updated_at" field.
func (rpc *RolePermissionCreate) SetUpdatedAt(t time.Time) *RolePermissionCreate {
	rpc.mutation.SetUpdatedAt(t)
	return rpc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (rpc *RolePermissionCreate) SetNillableUpdatedAt(t *time.Time) *RolePermissionCreate {
	if t != nil {
		rpc.SetUpdatedAt(*t)
	}
	return rpc
}

// SetCompanyID sets the "company_id" field.
func (rpc *RolePermissionCreate) SetCompanyID(u uuid.UUID) *RolePermissionCreate {
	rpc.mutation.SetCompanyID(u)
	return rpc
}

// SetNillableCompanyID sets the "company_id" field if the given value is not nil.
func (rpc *RolePermissionCreate) SetNillableCompanyID(u *uuid.UUID) *RolePermissionCreate {
	if u != nil {
		rpc.SetCompanyID(*u)
	}
	return rpc
}

// SetRoleID sets the "role_id" field.
func (rpc *RolePermissionCreate) SetRoleID(u uuid.UUID) *RolePermissionCreate {
	rpc.mutation.SetRoleID(u)
	return rpc
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (rpc *RolePermissionCreate) SetNillableRoleID(u *uuid.UUID) *RolePermissionCreate {
	if u != nil {
		rpc.SetRoleID(*u)
	}
	return rpc
}

// SetPermissionID sets the "permission_id" field.
func (rpc *RolePermissionCreate) SetPermissionID(u uuid.UUID) *RolePermissionCreate {
	rpc.mutation.SetPermissionID(u)
	return rpc
}

// SetNillablePermissionID sets the "permission_id" field if the given value is not nil.
func (rpc *RolePermissionCreate) SetNillablePermissionID(u *uuid.UUID) *RolePermissionCreate {
	if u != nil {
		rpc.SetPermissionID(*u)
	}
	return rpc
}

// SetID sets the "id" field.
func (rpc *RolePermissionCreate) SetID(u uuid.UUID) *RolePermissionCreate {
	rpc.mutation.SetID(u)
	return rpc
}

// SetCompany sets the "company" edge to the Company entity.
func (rpc *RolePermissionCreate) SetCompany(c *Company) *RolePermissionCreate {
	return rpc.SetCompanyID(c.ID)
}

// SetRole sets the "role" edge to the Role entity.
func (rpc *RolePermissionCreate) SetRole(r *Role) *RolePermissionCreate {
	return rpc.SetRoleID(r.ID)
}

// SetPermission sets the "permission" edge to the Permission entity.
func (rpc *RolePermissionCreate) SetPermission(p *Permission) *RolePermissionCreate {
	return rpc.SetPermissionID(p.ID)
}

// Mutation returns the RolePermissionMutation object of the builder.
func (rpc *RolePermissionCreate) Mutation() *RolePermissionMutation {
	return rpc.mutation
}

// Save creates the RolePermission in the database.
func (rpc *RolePermissionCreate) Save(ctx context.Context) (*RolePermission, error) {
	rpc.defaults()
	return withHooks(ctx, rpc.sqlSave, rpc.mutation, rpc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rpc *RolePermissionCreate) SaveX(ctx context.Context) *RolePermission {
	v, err := rpc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rpc *RolePermissionCreate) Exec(ctx context.Context) error {
	_, err := rpc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rpc *RolePermissionCreate) ExecX(ctx context.Context) {
	if err := rpc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rpc *RolePermissionCreate) defaults() {
	if _, ok := rpc.mutation.CreatedAt(); !ok {
		v := rolepermission.DefaultCreatedAt()
		rpc.mutation.SetCreatedAt(v)
	}
	if _, ok := rpc.mutation.UpdatedAt(); !ok {
		v := rolepermission.DefaultUpdatedAt()
		rpc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rpc *RolePermissionCreate) check() error {
	if _, ok := rpc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RolePermission.created_at"`)}
	}
	if _, ok := rpc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RolePermission.updated_at"`)}
	}
	return nil
}

func (rpc *RolePermissionCreate) sqlSave(ctx context.Context) (*RolePermission, error) {
	if err := rpc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rpc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rpc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	rpc.mutation.id = &_node.ID
	rpc.mutation.done = true
	return _node, nil
}

func (rpc *RolePermissionCreate) createSpec() (*RolePermission, *sqlgraph.CreateSpec) {
	var (
		_node = &RolePermission{config: rpc.config}
		_spec = sqlgraph.NewCreateSpec(rolepermission.Table, sqlgraph.NewFieldSpec(rolepermission.FieldID, field.TypeUUID))
	)
	if id, ok := rpc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := rpc.mutation.CreatedAt(); ok {
		_spec.SetField(rolepermission.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := rpc.mutation.UpdatedAt(); ok {
		_spec.SetField(rolepermission.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := rpc.mutation.CompanyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   rolepermission.CompanyTable,
			Columns: []string{rolepermission.CompanyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(company.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CompanyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := rpc.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   rolepermission.RoleTable,
			Columns: []string{rolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := rpc.mutation.PermissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   rolepermission.PermissionTable,
			Columns: []string{rolepermission.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PermissionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RolePermissionCreateBulk is the builder for creating many RolePermission entities in bulk.
type RolePermissionCreateBulk struct {
	config
	err      error
	builders []*RolePermissionCreate
}

// Save creates the RolePermission entities in the database.
func (rpcb *RolePermissionCreateBulk) Save(ctx context.Context) ([]*RolePermission, error) {
	if rpcb.err != nil {
		return nil, rpcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rpcb.builders))
	nodes := make([]*RolePermission, len(rpcb.builders))
	mutators := make([]Mutator, len(rpcb.builders))
	for i := range rpcb.builders {
		func(i int, root context.Context) {
			builder := rpcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RolePermissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rpcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rpcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rpcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rpcb *RolePermissionCreateBulk) SaveX(ctx context.Context) []*RolePermission {
	v, err := rpcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rpcb *RolePermissionCreateBulk) Exec(ctx context.Context) error {
	_, err := rpcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rpcb *RolePermissionCreateBulk) ExecX(ctx context.Context) {
	if err := rpcb.Exec(ctx); err != nil {
		panic(err)
	}
}
