// Code generated by ent, DO NOT EDIT.

package ent

import (
	"project/src/models/ent/company"
	"project/src/models/ent/permission"
	"project/src/models/ent/role"
	"project/src/models/ent/rolepermission"
	"project/src/models/ent/schema"
	"project/src/models/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	companyMixin := schema.Company{}.Mixin()
	companyMixinFields0 := companyMixin[0].Fields()
	_ = companyMixinFields0
	companyFields := schema.Company{}.Fields()
	_ = companyFields
	// companyDescCreatedAt is the schema descriptor for created_at field.
	companyDescCreatedAt := companyMixinFields0[1].Descriptor()
	// company.DefaultCreatedAt holds the default value on creation for the created_at field.
	company.DefaultCreatedAt = companyDescCreatedAt.Default.(func() time.Time)
	// companyDescUpdatedAt is the schema descriptor for updated_at field.
	companyDescUpdatedAt := companyMixinFields0[2].Descriptor()
	// company.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	company.DefaultUpdatedAt = companyDescUpdatedAt.Default.(func() time.Time)
	// company.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	company.UpdateDefaultUpdatedAt = companyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// companyDescIsDisabled is the schema descriptor for is_disabled field.
	companyDescIsDisabled := companyFields[1].Descriptor()
	// company.DefaultIsDisabled holds the default value on creation for the is_disabled field.
	company.DefaultIsDisabled = companyDescIsDisabled.Default.(bool)
	permissionMixin := schema.Permission{}.Mixin()
	permissionMixinFields0 := permissionMixin[0].Fields()
	_ = permissionMixinFields0
	permissionFields := schema.Permission{}.Fields()
	_ = permissionFields
	// permissionDescCreatedAt is the schema descriptor for created_at field.
	permissionDescCreatedAt := permissionMixinFields0[1].Descriptor()
	// permission.DefaultCreatedAt holds the default value on creation for the created_at field.
	permission.DefaultCreatedAt = permissionDescCreatedAt.Default.(func() time.Time)
	// permissionDescUpdatedAt is the schema descriptor for updated_at field.
	permissionDescUpdatedAt := permissionMixinFields0[2].Descriptor()
	// permission.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	permission.DefaultUpdatedAt = permissionDescUpdatedAt.Default.(func() time.Time)
	// permission.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	permission.UpdateDefaultUpdatedAt = permissionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// permissionDescRead is the schema descriptor for read field.
	permissionDescRead := permissionFields[2].Descriptor()
	// permission.DefaultRead holds the default value on creation for the read field.
	permission.DefaultRead = permissionDescRead.Default.(bool)
	// permissionDescWrite is the schema descriptor for write field.
	permissionDescWrite := permissionFields[3].Descriptor()
	// permission.DefaultWrite holds the default value on creation for the write field.
	permission.DefaultWrite = permissionDescWrite.Default.(bool)
	// permissionDescPatch is the schema descriptor for patch field.
	permissionDescPatch := permissionFields[4].Descriptor()
	// permission.DefaultPatch holds the default value on creation for the patch field.
	permission.DefaultPatch = permissionDescPatch.Default.(bool)
	// permissionDescDelete is the schema descriptor for delete field.
	permissionDescDelete := permissionFields[5].Descriptor()
	// permission.DefaultDelete holds the default value on creation for the delete field.
	permission.DefaultDelete = permissionDescDelete.Default.(bool)
	roleMixin := schema.Role{}.Mixin()
	roleMixinFields0 := roleMixin[0].Fields()
	_ = roleMixinFields0
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleMixinFields0[1].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	// roleDescUpdatedAt is the schema descriptor for updated_at field.
	roleDescUpdatedAt := roleMixinFields0[2].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() time.Time)
	// role.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	role.UpdateDefaultUpdatedAt = roleDescUpdatedAt.UpdateDefault.(func() time.Time)
	rolepermissionMixin := schema.RolePermission{}.Mixin()
	rolepermissionMixinFields0 := rolepermissionMixin[0].Fields()
	_ = rolepermissionMixinFields0
	rolepermissionFields := schema.RolePermission{}.Fields()
	_ = rolepermissionFields
	// rolepermissionDescCreatedAt is the schema descriptor for created_at field.
	rolepermissionDescCreatedAt := rolepermissionMixinFields0[1].Descriptor()
	// rolepermission.DefaultCreatedAt holds the default value on creation for the created_at field.
	rolepermission.DefaultCreatedAt = rolepermissionDescCreatedAt.Default.(func() time.Time)
	// rolepermissionDescUpdatedAt is the schema descriptor for updated_at field.
	rolepermissionDescUpdatedAt := rolepermissionMixinFields0[2].Descriptor()
	// rolepermission.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	rolepermission.DefaultUpdatedAt = rolepermissionDescUpdatedAt.Default.(func() time.Time)
	// rolepermission.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	rolepermission.UpdateDefaultUpdatedAt = rolepermissionDescUpdatedAt.UpdateDefault.(func() time.Time)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[2].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescIsDisabled is the schema descriptor for is_disabled field.
	userDescIsDisabled := userFields[4].Descriptor()
	// user.DefaultIsDisabled holds the default value on creation for the is_disabled field.
	user.DefaultIsDisabled = userDescIsDisabled.Default.(bool)
}
