// Code generated by utils/templates, DO NOT EDIT.

package ent

import (
	"project/utils/resource"
)

type CompanyResource = resource.Base[
	*Company,
	[]*Company,
	*CompanyQuery,
	[]*CreateCompanyInput,
	*UpdateCompanyInput,
	*User,
]

type PermissionResource = resource.Base[
	*Permission,
	[]*Permission,
	*PermissionQuery,
	[]*CreatePermissionInput,
	*UpdatePermissionInput,
	*User,
]

type RoleResource = resource.Base[
	*Role,
	[]*Role,
	*RoleQuery,
	[]*CreateRoleInput,
	*UpdateRoleInput,
	*User,
]

type RolePermissionResource = resource.Base[
	*RolePermission,
	[]*RolePermission,
	*RolePermissionQuery,
	[]*CreateRolePermissionInput,
	*UpdateRolePermissionInput,
	*User,
]

type UserResource = resource.Base[
	*User,
	[]*User,
	*UserQuery,
	[]*CreateUserInput,
	*UpdateUserInput,
	*User,
]
